apiVersion: v1
kind: Service
metadata:
  name: vue001ser
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
    - port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: vue001kube
