apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue001dep
spec:
  replicas: 2  # 원하는 경우 복제본 수를 지정
  selector:
    matchLabels:
      app: vue001kube
  template:
    metadata:
      labels:
        app: vue001kube
    spec:
      containers:
        - name: vue-container
          image: eodud3196/hotelity-frontend:v1.0.5
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            # 컨테이너가 동시에 두 개의 포트를 노출하는 경우, 서비스 정의도 필요할 수 있습니다.
